In [5]:
import numpy as np

In [10]:
def function3():
    arr = np.array([1, 7, 13, 105])
    print(arr)
    print(f"the size of memory occupied by array = {arr.nbytes}")
    
    

In [11]:
function3()

[  1   7  13 105]
the size of memory occupied by array = 32


In [12]:
import numpy as np

In [18]:
arr4 = np.zeros(10)

In [19]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
arr4 = np.ones(10)

In [24]:
print(arr4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
arr4 = np.ones(10)*5

In [26]:
print(arr4)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [27]:
arr4 = np.ones(10)*10
print(arr4)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [28]:
arr4 = np.ones(10)*20
print(arr4)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [29]:
arr4 = np.ones(10)*50
print(arr4)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [1]:
import numpy as np
arr2 = np.arange(30,70,1)
print(arr2)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [2]:
arr2 = np.arange(50,95,1)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [3]:
import numpy as np
arr2 = np.arange(20,80,2)
print(arr2)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [4]:
arr2 = np.arange(19,81,2)
print(arr2)

[19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65
 67 69 71 73 75 77 79]


In [5]:
import numpy as np
n4 = np.random.randint(10,40,15)
print(n4)

[15 15 38 39 22 10 35 21 13 38 39 32 26 19 26]


In [6]:
import numpy as np

In [8]:
n4 = np.random.randint(30,50,10)
print(n4)

[44 47 37 37 39 41 44 48 42 38]


In [9]:
n4 = np.random.randint(50,90,20)
print(n4)

[65 68 68 88 53 66 71 54 80 55 89 74 78 59 63 58 67 81 56 64]


In [10]:
import numpy as np
n1 = np.array([11, 22, 33, 44])
n2 = np.array([10, 20, 30, 40])
print(f"N1 ={n1}")
print(f"N2 ={n2}")
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)

N1 =[11 22 33 44]
N2 =[10 20 30 40]
[21 42 63 84]
[1 2 3 4]
[ 110  440  990 1760]
[1.1 1.1 1.1 1.1]


In [11]:
import numpy as np
m=np.arange(10,22).reshape((3,4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [12]:
import numpy as np
m= np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
#Question 2
import numpy as np

In [2]:
n1 = np.array([1, 4])
print(n1)
n2 = np.array([1, 2])
print(n2)

[1 4]
[1 2]


In [3]:
print("greater")
n1 = np.greater(n1, n2)
print(n1)

greater
[False  True]


In [4]:
print("greater_equal")
n1 = np.greater_equal(n1, n2)
print(n1)

greater_equal
[False False]


In [5]:
print("less")
n1 = np.less(n1, n2)
print(n1)

less
[ True  True]


In [6]:
#Question 14
import numpy as np

In [8]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
print(n1)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(f"Rows and Column are = {n1.shape}")

Rows and Column are = (2, 4)


In [10]:
#Question15
import numpy as np

In [11]:
n1 = np.diag([1,2,3,4,5])
print(n1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
#Question16
import numpy as np 

In [13]:
n1 = np.random.random((3,3,3))

In [14]:
print(n1)

[[[0.66167866 0.48303561 0.93772041]
  [0.28730158 0.33088738 0.48768108]
  [0.10600271 0.51846136 0.75803898]]

 [[0.81867906 0.5022703  0.50380138]
  [0.76408792 0.42752944 0.97104014]
  [0.63289898 0.62161231 0.27012098]]

 [[0.23639918 0.61591892 0.66652164]
  [0.45539493 0.60772549 0.55876092]
  [0.01758347 0.69306273 0.63577187]]]


In [15]:
#Question17
import numpy as np

In [16]:
n1 = np.random.randint(2,3,4)
print(n1)

[2 2 2 2]


In [17]:
#Question18
import numpy as np

In [18]:
list = [10,11,12,13,14,15]
print(list)

[10, 11, 12, 13, 14, 15]


In [19]:
n1 = np.array(list)
print(n1)

[10 11 12 13 14 15]


In [20]:
#Question19
import numpy as np

In [21]:
n1 = np.arange(2,11)
print(n1)

[ 2  3  4  5  6  7  8  9 10]


In [22]:
n1 = n1.reshape([3,3])
print(n1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [23]:
#Question20
import numpy as np

In [24]:
n1 = np.arange(12,38)
print(n1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [25]:
#Question21
import numpy as np

In [26]:
n1 = np.arange(0,10)
print(n1)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
n1 = n1[::-1]
print("Reverse Array:",n1)

Reverse Array: [9 8 7 6 5 4 3 2 1 0]


In [28]:
#Question22
import numpy as np

In [29]:
n1 = [8,6,5,4,7]
print(n1)

[8, 6, 5, 4, 7]


In [30]:
n1 = np.asfarray(n1)
print(n1)

[8. 6. 5. 4. 7.]


In [31]:
#Question23
import numpy as np

In [32]:
list = [1,2,3,4,5,6,7,8,9]
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [33]:
arr = np.array([list])
print(arr)

[[1 2 3 4 5 6 7 8 9]]


In [34]:
#Question24
import numpy as np

In [35]:
n1 = np.arange(0,10)
print(n1)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
print("Element wise remainder")
n1 = np.remainder(n1,5)
print(n1)

Element wise remainder
[0 1 2 3 4 0 1 2 3 4]


In [37]:
#Question25
import numpy as np

In [38]:
n1 = np.arange(20,50)
print(n1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [39]:
print("Element wise remainder")
n1 = np.remainder(n1,3)
print(n1)

Element wise remainder
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
